config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  
  resources :products do
    get :who_bought, on: :member
  end

  resources :support_requests, only: [ :index, :update ]

  scope '(:locale)' do

    resources :orders

    resources :line_items do
      collection do
        post :decrease
      end
    end

    resources :carts do
      collection do
        get :current_cart
        delete :destroy_new
      end
    end

    root 'store#index', as: 'store_index', via: [:get, :post]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
            current_item.increment(:quantity)
        else
            current_item = line_items.build(product_id: product.id)
            current_item.price = current_item.product.price
        end
        current_item
    end

    def decrease_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item.quantity >= 2
            current_item.quantity -= 1
        else
            current_item = current_item.destroy
        end
        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:create, :update, :decrease, :destroy, :destroy_new]
  before_action :set_cart2_show
  skip_before_action :authorize
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    # показать корзину активной сессии в любом случае
    # @cart = Cart.find(session[:cart_id])

    @cart = Cart.find(params[:id])
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    # @cart.destroy
    @cart.destroy if @cart.id == session[:cart_id]

    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Your cart is empty.' }
      format.js 
      format.json { head :no_content }
    end
  end

  def destroy_new
    @cart = Cart.find(params[:cart_id])
    @cart.destroy

    # session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.js 
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
  
    # Only allow a list of trusted parameters through.

    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to carts_url, notice: 'Invalid cart'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% if notice %><p id="notice"><%= notice %></p><% end %>

<%= render partial: 'carts/cart2' %>

app/views/carts/_cart2.html.erb
<article>
    <% if @cart.line_items.any? %>

    <h2><%= t('.title') %></h2>

    <table>
        <%= render(@cart.line_items) %>
        <br>
        <tfoot>
            <th colspan="2"> <%= t('.total') %> </th>
            <td class="price"><%= number_to_currency(@cart.total_price) %></td>
        </tfoot>
    </table>

    <div class="submit">
        <br>
        <%= button_to t('.empty'), @cart, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
        <br>
        <%= render 'my/button' %>
    </div>

    <% end %>
</article>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <div class="actions">
    <%= form.submit t('.submit') %>
  </div>
<% end %>

app/views/carts/_form2.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/_form_full.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/_form_short.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
cart = document.getElementById("cart")
cart.innerHTML = "<%= j render(@cart) %>"

notice = document.getElementById("notice")
if (notice) notice.style.display = "none"

app/views/carts/edit.html.erb
<h1><%= t('.edit') %></h1>

<%= render 'form', cart: @cart %>

<%= link_to t('.show'), @cart %> |
<%= link_to t('.back'), carts_url %>

app/views/carts/index.html.erb
<% if notice %><p id="notice"><%= notice %></p><% end %>

<h1><%= t('.carts') %></h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <p>
      <%= render 'my/currentcart' %>
    </p>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= t('.cart') %> <%= cart.id %></td>
        <td><%= link_to t('.show'), cart, method: :get %></td>
        <td><%= link_to t('.edit'), edit_cart_path(cart) %></td>
        <td><%= link_to 'D', cart, method: :delete, data: { confirm: 'Sure?' } %></td>
        <td><%= link_to t('.destroy'), destroy_new_carts_path(:cart_id => cart), method: :delete, data: { confirm: 'Sure?' } %></td>
      </tr>
    <% end %>
    <tr><p>
      <td><%= link_to t('.new'), new_cart_path %></td>
    </p></tr>
  </tbody>
</table>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_url %>

app/views/carts/show.html.erb
<%= render @cart %>

<br>
<%= button_to t('.back'), carts_url %>