config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  
  resources :products do
    get :who_bought, on: :member
  end

  resources :support_requests, only: [ :index, :update ]

  scope '(:locale)' do

    resources :orders

    resources :line_items do
      collection do
        post :decrease
      end
    end

    resources :carts do
      collection do
        get :current_cart
        delete :destroy_new
      end
    end

    root 'store#index', as: 'store_index', via: [:get, :post]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :line_items
    has_many :orders, through: :line_items
    before_destroy :ensure_not_referenced_by_any_line_item

    validates :title, :description, :image_url, presence: true
    validates :price, numericality: { greater_than_or_equal_to: 0.01 }
    validates :title, uniqueness: true
    validates :image_url, allow_blank: true, format: {
        with: %r{\.(gif|jpg|png)\z}i,
        message: 'must be a URL for GIF, JPG or PNG image.'
        }

    # Глава 07 задание
    validates :title, length: { minimum: 2 }

    private
    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, 'Line Items present')
            throw :abort
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_cart2_show
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order(:title)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @product }
      else
        puts @product.errors.full_messages
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @product }
        
        @products = Product.all.order(:title, :price)
        ActionCable.server.broadcast 'products', html: render_to_string('store/index', layout: false)
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
        format.json { render :json => @product.to_json(:include => :orders) }
        format.html
        format.xml
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t('.title') %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label t('.description') %>
    <%= form.text_area :description, rows: 10, cols: 60 %>
  </div>

  <div class="field">
    <%= form.label t('.image_url') %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label t('.price') %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit t('.submit') %>
  </div>
<% end %>

app/views/products/_product.html.erb
<ul class="catalog">
    <% cache @products do %>
        <% @products.each do |product| %>
            <% cache product do %>
                <li>
                <%= link_to line_items_path(product_id: product), method: :post, remote: true do %>
                    <%= image_tag(product.image_url) %>
                <% end %>
                <h2><%= product.title %></h2>
                <p>
                    <%= sanitize(product.description, length: 80) %>
                    <%= truncate(product.description, length: 40) %>
                </p>
                <div class="price">

                <% if product == @product %>
                    <div class="products-highlight">
                        <%= number_to_currency(product.price, unit: "₽", format: "%n %u") %>
                    </div>
                <% else %>
                    <div class="price">
                        <%= number_to_currency(product.price, unit: "₽", format: "%n %u") %>
                    </div>
                <% end %>

                    <%= button_to 'Add to Cart2', line_items_path(product_id: product), remote: true %>
                </div>
                </li>
            <% end %>
        <% end %>
    <% end %>
</ul>

app/views/products/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', product: @product %>

<%= link_to t('.show'), @product %> |
<%= link_to t('.back'), products_path %>

app/views/products/index.html.erb
<% if notice %><p id="notice"><%= notice %></p><% end %>

<h1><%= t('.title') %></h1>

<table>
  <tfoot>
    <tr>
      <td colspan="3">
        <%= link_to 'New Product', new_product_path %>
      </td>
    </tr>
  </tfoot>

  <tbody>
    <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="image">
          <%= image_tag(product.image_url, class: 'list_image') %>
        </td>       
        
        <td class="description">
          <h2><%= product.title %></h2>
          <p>
            <%= truncate(strip_tags(product.description), length: 20) %>
          </p>
          <p>
              <h3>
              <%= number_to_currency(
                  product.price, unit: "₽",
                  format: "%n %u",
                  strip_insignificant_zeros: true) 
              %>
            </h3>
          </p>
        </td>

        <td class="actions">
          <ul>
          <td>
            <li>
              <%= link_to  t('.show'), product %>
            </li>
            <li>
              <%= link_to  t('.edit'), edit_product_path(product) %>
            </li>
            <li>
              <%= link_to  t('.destroy'), product, method: :delete, data: { confirm: 'Are you sure?' } %>
            </li>
            <br>
            <li>
              <%= link_to  t('.whobought'), who_bought_product_path(product, format: :html), method: :get %>
            </li>
            <!--
            <li>
              <%= link_to 'Who bought XML', who_bought_product_path(product, format: :xml), method: :get %>
            </li>
            <li>
              <%= link_to 'Who bought JSON', who_bought_product_path(product, format: :json), method: :get %>
            </li>
            -->
          </td>
          </ul>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% if notice %><p id="notice"><%= notice %></p><% end %>

<p>
  <strong><%= t('.title') %></strong>
  <%= @product.title %>
</p>

<p>
  <strong><%= t('.description') %></strong>
  <%= @product.description %>
</p>

<p>
  <strong><%= t('.image_url') %></strong>
  <%= @product.image_url %>
</p>

<p>
  <strong><%= t('.price') %></strong>
  <%= @product.price %>
</p>

<%= link_to t('.edit'), edit_product_path(@product) %> |
<%= link_to t('.back'), products_path %>

app/views/products/who_bought.html.erb
<h3><%= t('.whobought') %> <%= @product.title %></h3>
 

<% for order in @product.orders %>
    <table>
        <p>
            <tr>
                <%= link_to order do %><%= t('.order') %><%= order.id %> <% end %>
            </tr>
        </p>
        <p>
            <tr>
                <td><%= t('.name') %></td>
                <td><%= order.name %></td>
            </tr>
            <tr>
                <td><%= t('.email') %></td>
                <td><%= order.email %><td><br>
            </tr>
                <td><%= t('.address') %></td>
                <td><%= order.address %><td><br>
            <tr>
                <td><%= t('.paytype') %></td>
                <td><%= order.pay_type %><td><br>
            </tr>
            <tr>
                <td><%= t('.date') %></td>
                <td><%= order.created_at %><td><br>
            </tr>
        </p>
    </table>
<% end %>