config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  
  resources :products do
    get :who_bought, on: :member
  end

  resources :support_requests, only: [ :index, :update ]

  scope '(:locale)' do

    resources :orders

    resources :line_items do
      collection do
        post :decrease
      end
    end

    resources :carts do
      collection do
        get :current_cart
        delete :destroy_new
      end
    end

    root 'store#index', as: 'store_index', via: [:get, :post]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart, optional: true

  def total_price
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create, :decrease, :destroy]
  before_action :set_cart2_show
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create

    # product = Product.find_by(params[:product_id])
    # в этом случае любое изменение количества продуктов в корзине
    # будь то создание нового line_item, добавление через Add to Cart или плюсом в самой корзине
    # изменяет только количество продукта с id=1
    # зато тест "creating a Line item" в test/system/line_item_test.rb проходит

    product = Product.find(params[:product_id])
    # в этом случае при кликах по кнопкам все работает нормально
    # но создание Line Item через веб-интерфейс в /line_items/new валится с ошибкой
    # Couldn't find Product without an ID
    # заодно тест "creating a Line item" в test/system/line_item_test.rb валится с той же ошибкой
    
    @line_item = @cart.add_product(product)

    session[:counter] = 0

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_index_url, notice: "Line item was successfully created"  }
        format.js   { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def decrease
    product = Product.find(params[:product_id])

    @line_item = @cart.decrease_product(product)
    
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_index_url }
        format.js
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { redirect_to store_index_url }
        format.js
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
    @cart.id = session[:cart_id]
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed'  }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t('.product') %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label t('.cart') %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit t('.update') %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
    <tr class="line-item-highlight">
<% else %>
    <tr>
<% end %>
    <td class="quantity"> <%= line_item.quantity %></td>
    <td> <%= line_item.product.title %> </td>
    <td class="price"> <%= number_to_currency(line_item.total_price) %> </td>
    
    <!-- 

    <td class="buttons">
        <%= button_to 'x', line_item, method: :delete, remote: true %>
    </td>
    
    <td class="buttons">
        <%= button_to "+", line_items_path(product_id: line_item.product_id), method: :post, remote: true %>
    </td>
    
    <td class="buttons">    
        <%= button_to "-", decrease_line_items_path(product_id: line_item.product_id), method: :post, remote: true %>
    </td>

    -->
</tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
    line_item.quantity,
    truncate(line_item.product.title, length: 50)) %>

app/views/line_items/create.js.erb
cart = document.getElementById("cart")
cart.innerHTML = "<%= j render(@cart) %>"

notice = document.getElementById("notice")
if (notice) notice.style.display = "none"

app/views/line_items/decrease.js.erb
cart = document.getElementById("cart")
cart.innerHTML = "<%= j render(@cart) %>"

app/views/line_items/destroy.js.erb
cart = document.getElementById("cart")
cart.innerHTML = "<%= j render(@cart) %>"

notice = document.getElementById("notice")
if (notice) notice.style.display = "none"

app/views/line_items/edit.html.erb
<h1><%= t('.editing') %></h1>

<%= render 'form', line_item: @line_item %>

<%= link_to t('.show'), @line_item %> |
<%= link_to t('.back'), line_items_path %>

app/views/line_items/index.html.erb
<% if notice %><p id="notice"><%= notice %></p><% end %>

<h1><%= t('.title') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('.product') %></th>
      <th><%= t('.cart') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to t('.show'), line_item %></td>
        <td><%= link_to t('.edit'), edit_line_item_path(line_item) %></td>
        <td><%= link_to t('.destroy'), line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_line_item_path %>

app/views/line_items/new.html.erb
<h1><%= t('.new') %></h1>

<%= render 'form', line_item: @line_item %>

<%= link_to t('.back'), line_items_path %>

app/views/line_items/show.html.erb
<% if notice %><p id="notice"><%= notice %></p><% end %>

<p>
  <strong><%= t('.product') %></strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong><%= t('.cart') %></strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to t('.edit'), edit_line_item_path(@line_item) %> |
<%= link_to t('.back'), line_items_path %>