config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  
  resources :products do
    get :who_bought, on: :member
  end

  resources :support_requests, only: [ :index, :update ]

  scope '(:locale)' do

    resources :orders

    resources :line_items do
      collection do
        post :decrease
      end
    end

    resources :carts do
      collection do
        get :current_cart
        delete :destroy_new
      end
    end

    root 'store#index', as: 'store_index', via: [:get, :post]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
    </script>
    <%= javascript_pack_tag 'locale_switcher', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <header class="main">

      <aside>
        <%= form_tag store_index_path, class: 'locale' do %>
          <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
          <%= submit_tag 'submit', id: "submit_locale_change" %>
        <% end %>
      </aside>

      <%= image_tag 'ruby0.png', alt: 'Project 1' %>
      <h1><%= @page_title %></h1>
    </header>

    <section class="content">

      <nav class="side_nav">
        <ul>

          <li><%= link_to t('.home'), store_index_url %></li>
          <li><%= link_to t('.products'), products_url %></li>
          <li><%= link_to t('.carts'), carts_url %></li>
          <li><%= link_to t('.line_items'), line_items_url %></li>
          <li><%= link_to t('.login'), users_url %></li>
          <li><%= link_to t('.new_user'), new_user_path %></li>

          <!--
          <li><%= @show_msg1 %><%= @show_msg2 %>&nbsp</li>
          -->

          <% if session[:user_id] %>
            <nav class="logged_in_nav">
              <ul>
                <li><%= link_to t('.orders'), orders_url %></li>
                <li><%= link_to t('.logout'), logout_path, method: :delete %></li>
              </ul>
            </nav>
          <% end %>

          <br>
          <div id="cart" class="carts">
            <%= render_if @cart && @cart.line_items.any?, partial: 'carts/cart2' %>              
          </div>
        </ul>

      </nav>

      <main class='<%= controller.controller_name %>'>
        <%= yield %>
      </main>

    </section>
  </body>
</html>